// ─── DSA TOPICS — FAANG Interview Prep ───────────────────────────────────────
// 210+ problems organized by category · Most asked in Google, Amazon, Meta, Microsoft
// status: 'todo' | 'learning' | 'done'

export const DSA_CATEGORIES = [
  {
    id: 'arrays',
    label: 'Arrays & Strings',
    emoji: '📊',
    color: '#10b981',
    topics: [
      { id: 'two-pointers',           label: 'Two Pointers',                        diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/' },
      { id: 'sliding-window',         label: 'Sliding Window',                      diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/' },
      { id: 'prefix-sum',             label: 'Prefix Sum / Running Sum',            diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/running-sum-of-1d-array/' },
      { id: 'kadane',                 label: "Kadane's Algorithm",                  diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/maximum-subarray/' },
      { id: 'dutch-flag',             label: 'Dutch National Flag / Sort Colors',   diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/sort-colors/' },
      { id: 'matrix-traversal',       label: 'Matrix Traversal / Flood Fill',       diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/flood-fill/' },
      { id: 'spiral-matrix',          label: 'Spiral / Rotate Matrix',              diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/spiral-matrix/' },
      { id: 'string-manipulation',    label: 'String Manipulation / Reverse',       diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/reverse-string/' },
      { id: 'anagram-problems',       label: 'Anagram / Frequency Map',             diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/valid-anagram/' },
      { id: 'palindrome',             label: 'Palindrome Patterns',                 diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/valid-palindrome/' },
      { id: 'substring-search',       label: 'Substring Search / KMP',              diff: 'hard',   freq: 'medium',    link: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/' },
      { id: 'trapping-rain',          label: 'Trapping Rain Water',                 diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/trapping-rain-water/' },
      { id: 'container-water',        label: 'Container With Most Water',           diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/container-with-most-water/' },
      { id: 'product-except-self',    label: 'Product of Array Except Self',        diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/product-of-array-except-self/' },
      { id: 'max-product-subarray',   label: 'Maximum Product Subarray',            diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/maximum-product-subarray/' },
      { id: 'three-sum',              label: '3Sum / 4Sum',                         diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/3sum/' },
      { id: 'next-permutation',       label: 'Next Permutation',                    diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/next-permutation/' },
      { id: 'find-duplicate',         label: 'Find the Duplicate Number',           diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/find-the-duplicate-number/' },
      { id: 'longest-consecutive',    label: 'Longest Consecutive Sequence',        diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/longest-consecutive-sequence/' },
      { id: 'rotate-array',           label: 'Rotate Array / Image',                diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/rotate-array/' },
      { id: 'set-matrix-zeroes',      label: 'Set Matrix Zeroes',                   diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/set-matrix-zeroes/' },
      { id: 'min-size-subarray',      label: 'Minimum Size Subarray Sum',           diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/minimum-size-subarray-sum/' },
      { id: 'find-all-anagrams',      label: 'Find All Anagrams in String',         diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/find-all-anagrams-in-a-string/' },
      { id: 'first-missing-positive', label: 'First Missing Positive',              diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/first-missing-positive/' },
      { id: 'median-two-arrays',      label: 'Median of Two Sorted Arrays',         diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/median-of-two-sorted-arrays/' },
    ],
  },
  {
    id: 'binary-search',
    label: 'Binary Search',
    emoji: '🔍',
    color: '#6366f1',
    topics: [
      { id: 'bs-classic',        label: 'Classic Binary Search',              diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/binary-search/' },
      { id: 'bs-first-last',     label: 'First & Last Position',              diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/' },
      { id: 'bs-rotated',        label: 'Search in Rotated Sorted Array',     diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/search-in-rotated-sorted-array/' },
      { id: 'bs-min-rotated',    label: 'Find Min in Rotated Array',          diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/' },
      { id: 'bs-on-answer',      label: 'Binary Search on Answer',            diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/' },
      { id: 'bs-2d',             label: 'Search in 2D Matrix',                diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/search-a-2d-matrix/' },
      { id: 'bs-peak',           label: 'Find Peak Element',                  diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/find-peak-element/' },
      { id: 'bs-koko',           label: 'Koko Eating Bananas',                diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/koko-eating-bananas/' },
      { id: 'bs-k-closest',      label: 'K Closest Elements',                 diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/find-k-closest-elements/' },
      { id: 'bs-split-array',    label: 'Split Array Largest Sum',            diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/split-array-largest-sum/' },
      { id: 'bs-aggressive-cows',label: 'Aggressive Cows (BS on Answer)',     diff: 'hard',   freq: 'high',      link: 'https://www.geeksforgeeks.org/problems/aggressive-cows/0' },
      { id: 'bs-allocate-books', label: 'Allocate Books / Painter Partition', diff: 'hard',   freq: 'high',      link: 'https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1' },
      { id: 'bs-sqrt',           label: 'Sqrt(x) / Nth Root of M',           diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/sqrtx/' },
      { id: 'bs-missing-sorted', label: 'Kth Missing Positive Number',        diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/kth-missing-positive-number/' },
      { id: 'bs-row-max-ones',   label: 'Row with Maximum 1s',                diff: 'medium', freq: 'medium',    link: 'https://www.geeksforgeeks.org/problems/row-with-max-1s0023/1' },
    ],
  },
  {
    id: 'linked-lists',
    label: 'Linked Lists',
    emoji: '🔗',
    color: '#f59e0b',
    topics: [
      { id: 'll-reversal',         label: 'Reversal (Iterative & Recursive)',   diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/reverse-linked-list/' },
      { id: 'll-cycle',            label: 'Cycle Detection — Floyd\'s',         diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/linked-list-cycle/' },
      { id: 'll-merge-sorted',     label: 'Merge Two Sorted Lists',             diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/merge-two-sorted-lists/' },
      { id: 'll-nth-from-end',     label: 'Remove Nth Node from End',           diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/' },
      { id: 'll-intersection',     label: 'Intersection of Two Lists',          diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/intersection-of-two-linked-lists/' },
      { id: 'll-reorder',          label: 'Reorder List',                       diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/reorder-list/' },
      { id: 'll-reverse-groups',   label: 'Reverse Nodes in K-Groups',          diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/reverse-nodes-in-k-group/' },
      { id: 'll-lru',              label: 'LRU Cache (HashMap + DLL)',          diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/lru-cache/' },
      { id: 'll-add-two-numbers',  label: 'Add Two Numbers',                    diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/add-two-numbers/' },
      { id: 'll-palindrome',       label: 'Palindrome Linked List',             diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/palindrome-linked-list/' },
      { id: 'll-odd-even',         label: 'Odd Even Linked List',               diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/odd-even-linked-list/' },
      { id: 'll-copy-random',      label: 'Copy List with Random Pointer',      diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/copy-list-with-random-pointer/' },
      { id: 'll-sort',             label: 'Sort Linked List (Merge Sort)',       diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/sort-list/' },
      { id: 'll-rotate',           label: 'Rotate Linked List',                 diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/rotate-list/' },
    ],
  },
  {
    id: 'trees',
    label: 'Trees & Binary Search Trees',
    emoji: '🌳',
    color: '#34d399',
    topics: [
      { id: 'tree-bfs',             label: 'BFS / Level Order Traversal',          diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/binary-tree-level-order-traversal/' },
      { id: 'tree-dfs',             label: 'DFS — Pre / In / Post Order',          diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/binary-tree-inorder-traversal/' },
      { id: 'tree-height',          label: 'Height / Diameter of Tree',            diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/' },
      { id: 'bst-validate',         label: 'Validate BST',                         diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/validate-binary-search-tree/' },
      { id: 'bst-operations',       label: 'BST Insert / Delete / Search',         diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/search-in-a-binary-search-tree/' },
      { id: 'tree-lca',             label: 'Lowest Common Ancestor',               diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/' },
      { id: 'tree-path-sum',        label: 'Path Sum I & II',                      diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/path-sum/' },
      { id: 'tree-construct',       label: 'Construct Tree from Traversals',       diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/' },
      { id: 'tree-serialize',       label: 'Serialize / Deserialize Binary Tree',  diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/' },
      { id: 'tree-right-view',      label: 'Right / Left View of Tree',            diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/binary-tree-right-side-view/' },
      { id: 'tree-flatten',         label: 'Flatten Tree to Linked List',          diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/' },
      { id: 'tree-symmetric',       label: 'Symmetric Tree / Same Tree',           diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/symmetric-tree/' },
      { id: 'tree-max-path-sum',    label: 'Binary Tree Maximum Path Sum',         diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/' },
      { id: 'tree-zigzag',          label: 'Zigzag Level Order Traversal',         diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/' },
      { id: 'bst-kth-smallest',     label: 'Kth Smallest Element in BST',          diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/' },
      { id: 'tree-count-good-nodes',label: 'Count Good Nodes in Binary Tree',      diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/count-good-nodes-in-binary-tree/' },
      { id: 'tree-vertical-order',  label: 'Vertical Order Traversal',             diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/' },
      { id: 'tree-width',           label: 'Maximum Width of Binary Tree',         diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/maximum-width-of-binary-tree/' },
      { id: 'bst-convert-sorted',   label: 'Convert Sorted Array to BST',          diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/' },
      { id: 'tree-boundary',        label: 'Boundary Traversal of Binary Tree',    diff: 'medium', freq: 'medium',    link: 'https://www.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1' },
    ],
  },
  {
    id: 'graphs',
    label: 'Graphs',
    emoji: '🕸️',
    color: '#ec4899',
    topics: [
      { id: 'graph-bfs',            label: 'BFS — Shortest Path & Grid',        diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/rotting-oranges/' },
      { id: 'graph-dfs',            label: 'DFS — Connected Components',        diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/number-of-islands/' },
      { id: 'graph-topo',           label: 'Topological Sort (Kahn\'s + DFS)',  diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/course-schedule/' },
      { id: 'graph-union-find',     label: 'Union-Find / Disjoint Set',         diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/number-of-provinces/' },
      { id: 'graph-dijkstra',       label: "Dijkstra's Shortest Path",          diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/network-delay-time/' },
      { id: 'graph-cycle',          label: 'Cycle Detection — Directed Graph',  diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/course-schedule-ii/' },
      { id: 'graph-bipartite',      label: 'Bipartite Graph Check',             diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/is-graph-bipartite/' },
      { id: 'graph-islands',        label: 'Number of Islands & Variants',      diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/number-of-islands/' },
      { id: 'graph-mst',            label: "Kruskal's & Prim's MST",           diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/min-cost-to-connect-all-points/' },
      { id: 'graph-floyd',          label: 'Floyd-Warshall (All Pairs SP)',     diff: 'hard',   freq: 'medium',    link: 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/' },
      { id: 'graph-word-ladder',    label: 'Word Ladder (BFS)',                 diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/word-ladder/' },
      { id: 'graph-pacific-atlantic',label: 'Pacific Atlantic Water Flow',      diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/pacific-atlantic-water-flow/' },
      { id: 'graph-clone',          label: 'Clone Graph',                       diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/clone-graph/' },
      { id: 'graph-alien-dict',     label: 'Alien Dictionary (Topo Sort)',      diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/alien-dictionary/' },
      { id: 'graph-critical-conn',  label: 'Critical Connections / Bridges',   diff: 'hard',   freq: 'medium',    link: 'https://leetcode.com/problems/critical-connections-in-a-network/' },
      { id: 'graph-accounts-merge', label: 'Accounts Merge (Union-Find)',       diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/accounts-merge/' },
      { id: 'graph-shortest-binary',label: 'Shortest Path in Binary Matrix',   diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/' },
      { id: 'graph-bellman-ford',   label: 'Bellman-Ford Algorithm',            diff: 'hard',   freq: 'medium',    link: 'https://www.geeksforgeeks.org/problems/distance-from-the-source-bellman-ford-algorithm/1' },
    ],
  },
  {
    id: 'dp',
    label: 'Dynamic Programming',
    emoji: '⚡',
    color: '#8b5cf6',
    topics: [
      { id: 'dp-fibonacci',       label: 'Fibonacci / Climbing Stairs',          diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/climbing-stairs/' },
      { id: 'dp-house-robber',    label: 'House Robber I & II',                  diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/house-robber/' },
      { id: 'dp-knapsack-01',     label: '0/1 Knapsack',                         diff: 'medium', freq: 'very-high', link: 'https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1' },
      { id: 'dp-unbounded',       label: 'Unbounded Knapsack / Coin Change',     diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/coin-change/' },
      { id: 'dp-lcs',             label: 'Longest Common Subsequence',           diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/longest-common-subsequence/' },
      { id: 'dp-lis',             label: 'Longest Increasing Subsequence',       diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/longest-increasing-subsequence/' },
      { id: 'dp-grid',            label: 'Grid DP — Unique Paths & Min Path',    diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/unique-paths/' },
      { id: 'dp-partition',       label: 'Partition / Subset Sum',               diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/partition-equal-subset-sum/' },
      { id: 'dp-palindrome',      label: 'Longest Palindromic Substring',        diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/longest-palindromic-substring/' },
      { id: 'dp-state-machine',   label: 'Stock Buy & Sell (State Machine)',     diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/' },
      { id: 'dp-interval',        label: 'Interval DP — Burst Balloons',         diff: 'hard',   freq: 'medium',    link: 'https://leetcode.com/problems/burst-balloons/' },
      { id: 'dp-bitmask',         label: 'Bitmask DP',                           diff: 'hard',   freq: 'low',       link: 'https://leetcode.com/problems/beautiful-arrangement/' },
      { id: 'dp-edit-distance',   label: 'Edit Distance (Levenshtein)',          diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/edit-distance/' },
      { id: 'dp-word-break',      label: 'Word Break I & II',                    diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/word-break/' },
      { id: 'dp-decode-ways',     label: 'Decode Ways',                          diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/decode-ways/' },
      { id: 'dp-stock-cooldown',  label: 'Stock with Cooldown / K Transactions', diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/' },
      { id: 'dp-distinct-subseq', label: 'Distinct Subsequences',               diff: 'hard',   freq: 'medium',    link: 'https://leetcode.com/problems/distinct-subsequences/' },
      { id: 'dp-regex',           label: 'Regular Expression Matching',          diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/regular-expression-matching/' },
      { id: 'dp-wildcard',        label: 'Wildcard Matching',                    diff: 'hard',   freq: 'medium',    link: 'https://leetcode.com/problems/wildcard-matching/' },
      { id: 'dp-triangle',        label: 'Triangle — Minimum Path Sum',          diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/triangle/' },
      { id: 'dp-coin-change-2',   label: 'Coin Change II — Number of Ways',     diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/coin-change-ii/' },
      { id: 'dp-max-square',      label: 'Maximal Square in Matrix',             diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/maximal-square/' },
      { id: 'dp-jump-game',       label: 'Jump Game — DP Approach',              diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/jump-game/' },
      { id: 'dp-painting-fence',  label: 'Painting Fence / Paint Houses',        diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/paint-house/' },
      { id: 'dp-min-coins',       label: 'Minimum Coins / Rod Cutting',          diff: 'medium', freq: 'high',      link: 'https://www.geeksforgeeks.org/problems/coin-change2448/1' },
    ],
  },
  {
    id: 'stack-queue',
    label: 'Stack, Queue & Heap',
    emoji: '📦',
    color: '#f97316',
    topics: [
      { id: 'stack-valid-parens',  label: 'Valid Parentheses / Brackets',     diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/valid-parentheses/' },
      { id: 'monotonic-stack',     label: 'Monotonic Stack — Next Greater',   diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/next-greater-element-i/' },
      { id: 'min-stack',           label: 'Min Stack / Max Stack Design',      diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/min-stack/' },
      { id: 'queue-stack',         label: 'Queue using Stack & Vice Versa',   diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/implement-queue-using-stacks/' },
      { id: 'heap-kth-largest',    label: 'Kth Largest Element',              diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
      { id: 'heap-top-k',          label: 'Top K Frequent Elements',          diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/top-k-frequent-elements/' },
      { id: 'heap-merge-k',        label: 'Merge K Sorted Lists',             diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/merge-k-sorted-lists/' },
      { id: 'heap-median',         label: 'Median from Data Stream',          diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/find-median-from-data-stream/' },
      { id: 'sliding-max',         label: 'Sliding Window Maximum (Deque)',   diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/sliding-window-maximum/' },
      { id: 'daily-temperatures',  label: 'Daily Temperatures',               diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/daily-temperatures/' },
      { id: 'largest-histogram',   label: 'Largest Rectangle in Histogram',  diff: 'hard',   freq: 'very-high', link: 'https://leetcode.com/problems/largest-rectangle-in-histogram/' },
      { id: 'asteroid-collision',  label: 'Asteroid Collision',               diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/asteroid-collision/' },
      { id: 'online-stock-span',   label: 'Online Stock Span',                diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/online-stock-span/' },
      { id: 'task-scheduler',      label: 'Task Scheduler',                   diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/task-scheduler/' },
      { id: 'k-points-origin',     label: 'K Closest Points to Origin',      diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/k-closest-points-to-origin/' },
    ],
  },
  {
    id: 'hashing',
    label: 'Hashing & Sorting',
    emoji: '#️⃣',
    color: '#06b6d4',
    topics: [
      { id: 'hash-two-sum',        label: 'Two Sum / Three Sum / Four Sum',    diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/two-sum/' },
      { id: 'hash-subarray-sum',   label: 'Subarray Sum Equals K',             diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/subarray-sum-equals-k/' },
      { id: 'hash-group-anagram',  label: 'Group Anagrams',                    diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/group-anagrams/' },
      { id: 'sorting-merge',       label: 'Merge Sort / Count Inversions',     diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/sort-an-array/' },
      { id: 'sorting-quick',       label: 'Quick Sort / Quick Select',         diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
      { id: 'intervals',           label: 'Merge Intervals',                   diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/merge-intervals/' },
      { id: 'custom-sort',         label: 'Custom Sort / Comparator',          diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/custom-sort-string/' },
      { id: 'insert-interval',     label: 'Insert Interval',                   diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/insert-interval/' },
      { id: 'meeting-rooms',       label: 'Meeting Rooms I & II',              diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/meeting-rooms-ii/' },
      { id: 'count-inversions',    label: 'Count Inversions in Array',         diff: 'medium', freq: 'high',      link: 'https://www.geeksforgeeks.org/problems/inversion-of-array-1587115620/1' },
      { id: 'sort-by-frequency',   label: 'Sort Characters By Frequency',      diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/sort-characters-by-frequency/' },
      { id: 'wiggle-sort',         label: 'Wiggle Sort / Sort Array by Parity',diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/sort-array-by-parity/' },
      { id: 'minimum-platforms',   label: 'Minimum Number of Platforms',       diff: 'medium', freq: 'high',      link: 'https://www.geeksforgeeks.org/problems/minimum-platforms-1587115620/1' },
      { id: 'four-sum',            label: '4Sum — General k-Sum Pattern',      diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/4sum/' },
    ],
  },
  {
    id: 'backtracking',
    label: 'Backtracking & Recursion',
    emoji: '🔄',
    color: '#a78bfa',
    topics: [
      { id: 'bt-subsets',               label: 'Subsets / Power Set',               diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/subsets/' },
      { id: 'bt-permutations',          label: 'Permutations (With/Without Dups)',  diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/permutations/' },
      { id: 'bt-combinations',          label: 'Combination Sum I & II',            diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/combination-sum/' },
      { id: 'bt-nqueens',               label: 'N-Queens',                          diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/n-queens/' },
      { id: 'bt-word-search',           label: 'Word Search in Grid',               diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/word-search/' },
      { id: 'bt-palindrome-partition',  label: 'Palindrome Partitioning',           diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/palindrome-partitioning/' },
      { id: 'bt-sudoku',                label: 'Sudoku Solver',                     diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/sudoku-solver/' },
      { id: 'bt-letter-combo',          label: 'Letter Combinations of Phone Num',  diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/' },
      { id: 'bt-generate-parens',       label: 'Generate Parentheses',              diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/generate-parentheses/' },
      { id: 'bt-expression-add-ops',    label: 'Expression Add Operators',          diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/expression-add-operators/' },
      { id: 'bt-rat-maze',              label: 'Rat in a Maze',                     diff: 'medium', freq: 'medium',    link: 'https://www.geeksforgeeks.org/problems/rat-in-a-maze-problem/1' },
      { id: 'bt-word-search-ii',        label: 'Word Search II (Trie + BT)',        diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/word-search-ii/' },
    ],
  },
  {
    id: 'greedy',
    label: 'Greedy & Math',
    emoji: '💡',
    color: '#fbbf24',
    topics: [
      { id: 'greedy-activity',     label: 'Activity Selection / Non-overlapping',  diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/non-overlapping-intervals/' },
      { id: 'greedy-jump-game',    label: 'Jump Game I & II',                      diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/jump-game/' },
      { id: 'greedy-gas-station',  label: 'Gas Station',                           diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/gas-station/' },
      { id: 'bit-xor',             label: 'XOR Tricks — Single Number I/II/III',  diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/single-number/' },
      { id: 'bit-count',           label: 'Count Set Bits / Number of 1 Bits',    diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/number-of-1-bits/' },
      { id: 'math-prime',          label: 'Sieve of Eratosthenes / Count Primes', diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/count-primes/' },
      { id: 'math-gcd',            label: 'GCD, LCM, Modular Arithmetic',         diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/find-greatest-common-divisor-of-array/' },
      { id: 'greedy-candy',        label: 'Candy Distribution',                   diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/candy/' },
      { id: 'greedy-fractional-ks',label: 'Fractional Knapsack',                  diff: 'medium', freq: 'high',      link: 'https://www.geeksforgeeks.org/problems/fractional-knapsack-1587115620/1' },
      { id: 'bit-power-of-two',    label: 'Power of Two / Reverse Bits',          diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/power-of-two/' },
      { id: 'greedy-min-arrows',   label: 'Minimum Arrows to Burst Balloons',     diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/' },
      { id: 'math-pow',            label: 'Pow(x, n) — Fast Exponentiation',      diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/powx-n/' },
    ],
  },
  {
    id: 'tries',
    label: 'Tries (Prefix Trees)',
    emoji: '🌐',
    color: '#22d3ee',
    topics: [
      { id: 'trie-implement',       label: 'Implement Trie (Prefix Tree)',        diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
      { id: 'trie-word-search',     label: 'Design Add and Search Words',         diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/' },
      { id: 'trie-longest-word',    label: 'Longest Word in Dictionary',          diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/longest-word-in-dictionary/' },
      { id: 'trie-replace-words',   label: 'Replace Words',                       diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/replace-words/' },
      { id: 'trie-max-xor',         label: 'Maximum XOR of Two Numbers',          diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/' },
      { id: 'trie-autocomplete',    label: 'Search Autocomplete System',          diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/search-suggestions-system/' },
      { id: 'trie-magic-dict',      label: 'Implement Magic Dictionary',          diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/implement-magic-dictionary/' },
      { id: 'trie-prefix-max-xor',  label: 'Maximum XOR With an Element',        diff: 'hard',   freq: 'medium',    link: 'https://leetcode.com/problems/maximum-xor-with-an-element-from-array/' },
    ],
  },
  {
    id: 'bit-manipulation',
    label: 'Bit Manipulation',
    emoji: '🔢',
    color: '#f472b6',
    topics: [
      { id: 'bit-single-number',     label: 'Single Number I — XOR',             diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/single-number/' },
      { id: 'bit-single-number-ii',  label: 'Single Number II — Bit Count',      diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/single-number-ii/' },
      { id: 'bit-counting',          label: 'Counting Bits (DP + Bit)',           diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/counting-bits/' },
      { id: 'bit-reverse',           label: 'Reverse Bits',                       diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/reverse-bits/' },
      { id: 'bit-sum-no-plus',       label: 'Sum of Two Integers Without +',      diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/sum-of-two-integers/' },
      { id: 'bit-missing',           label: 'Missing Number — XOR Trick',         diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/missing-number/' },
      { id: 'bit-power-set',         label: 'Power Set Using Bitmask',            diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/subsets/' },
      { id: 'bit-hamming',           label: 'Hamming Distance',                   diff: 'easy',   freq: 'medium',    link: 'https://leetcode.com/problems/hamming-distance/' },
    ],
  },
  {
    id: 'design',
    label: 'System Design — LLD',
    emoji: '🏗️',
    color: '#fb923c',
    topics: [
      { id: 'design-hashmap',        label: 'Design HashMap',                      diff: 'easy',   freq: 'high',      link: 'https://leetcode.com/problems/design-hashmap/' },
      { id: 'design-lru',            label: 'LRU Cache',                           diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/lru-cache/' },
      { id: 'design-lfu',            label: 'LFU Cache',                           diff: 'hard',   freq: 'high',      link: 'https://leetcode.com/problems/lfu-cache/' },
      { id: 'design-twitter',        label: 'Design Twitter',                      diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/design-twitter/' },
      { id: 'design-trie',           label: 'Design Trie / Autocomplete',          diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/implement-trie-prefix-tree/' },
      { id: 'design-circular-queue', label: 'Design Circular Queue',               diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/design-circular-queue/' },
      { id: 'design-linked-list',    label: 'Design Linked List',                  diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/design-linked-list/' },
      { id: 'design-iterator',       label: 'Flatten Nested List Iterator',        diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/flatten-nested-list-iterator/' },
      { id: 'design-rate-limiter',   label: 'Design Hit Counter / Rate Limiter',   diff: 'medium', freq: 'very-high', link: 'https://leetcode.com/problems/design-hit-counter/' },
      { id: 'design-snake-game',     label: 'Design Snake Game',                   diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/design-snake-game/' },
    ],
  },
  {
    id: 'recursion-dc',
    label: 'Recursion & Divide & Conquer',
    emoji: '⚔️',
    color: '#a3e635',
    topics: [
      { id: 'dc-merge-sort',          label: 'Merge Sort Implementation',           diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/sort-an-array/' },
      { id: 'dc-quick-sort',          label: 'Quick Sort Implementation',           diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/sort-an-array/' },
      { id: 'dc-count-range-sum',     label: 'Count of Range Sum',                  diff: 'hard',   freq: 'medium',    link: 'https://leetcode.com/problems/count-of-range-sum/' },
      { id: 'dc-majority-element',    label: 'Majority Element (Boyer-Moore)',       diff: 'easy',   freq: 'very-high', link: 'https://leetcode.com/problems/majority-element/' },
      { id: 'dc-pow-x-n',             label: 'Fast Power — Divide & Conquer',       diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/powx-n/' },
      { id: 'dc-beautiful-array',     label: 'Beautiful Array',                     diff: 'hard',   freq: 'low',       link: 'https://leetcode.com/problems/beautiful-array/' },
      { id: 'dc-different-ways',      label: 'Different Ways to Add Parentheses',   diff: 'medium', freq: 'medium',    link: 'https://leetcode.com/problems/different-ways-to-add-parentheses/' },
      { id: 'dc-kth-largest-dc',      label: 'Kth Largest via Quick Select',        diff: 'medium', freq: 'high',      link: 'https://leetcode.com/problems/kth-largest-element-in-an-array/' },
    ],
  },
];

export const TOTAL_TOPICS = DSA_CATEGORIES.reduce((s, c) => s + c.topics.length, 0);

export const DIFF_CONFIG = {
  easy:   { label: 'Easy',   color: '#10b981', bg: 'rgba(16,185,129,0.12)',  border: 'rgba(16,185,129,0.25)' },
  medium: { label: 'Medium', color: '#f59e0b', bg: 'rgba(245,158,11,0.12)', border: 'rgba(245,158,11,0.25)' },
  hard:   { label: 'Hard',   color: '#f87171', bg: 'rgba(248,113,113,0.12)',border: 'rgba(248,113,113,0.25)' },
};

export const FREQ_CONFIG = {
  'very-high': { label: '🔥 Must Know',    color: '#f97316' },
  'high':      { label: '⭐ Important',    color: '#fbbf24' },
  'medium':    { label: '👍 Good to Know', color: '#94a3b8' },
  'low':       { label: '📚 Deep Dive',    color: '#64748b' },
};
