// ─── FREE RESOURCES — Curated learning materials ─────────────────────────────
// All links are 100% free. Premium shows a curated "best of" filtered view.

export const RESOURCE_CATEGORIES = [
  // ─── DSA PRACTICE ──────────────────────────────────────────────────────────
  {
    id: 'dsa-practice',
    label: 'DSA Practice',
    emoji: '💻',
    color: '#10b981',
    resources: [
      {
        id: 'leetcode',
        title: 'LeetCode',
        description: 'The gold standard for coding interview prep. Start with NeetCode 150 or Blind 75.',
        url: 'https://leetcode.com',
        type: 'platform',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'practice', 'problems'],
      },
      {
        id: 'neetcode',
        title: 'NeetCode.io',
        description: 'Free curated roadmap with video solutions for top 150 interview problems.',
        url: 'https://neetcode.io',
        type: 'platform',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'roadmap', 'video'],
      },
      {
        id: 'striver',
        title: "Striver's A2Z DSA Sheet",
        description: '455 problems organized by topic. Best structured sheet for FAANG prep.',
        url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2',
        type: 'sheet',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'sheet', 'structured'],
      },
      {
        id: 'blind-75',
        title: 'Blind 75 LeetCode List',
        description: 'The classic 75 must-solve problems covering all key patterns. Minimum viable prep.',
        url: 'https://leetcode.com/discuss/general-discussion/460599/blind-75-leetcode-questions',
        type: 'sheet',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'sheet', 'faang'],
      },
      {
        id: 'gfg',
        title: 'GeeksforGeeks',
        description: 'India\'s #1 CS resource — DSA articles, interview experiences, and problems.',
        url: 'https://www.geeksforgeeks.org',
        type: 'platform',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'articles', 'india', 'cs-fundamentals'],
      },
      {
        id: 'cses',
        title: 'CSES Problem Set',
        description: '300 problems from easy to hard. Great for building algorithmic intuition.',
        url: 'https://cses.fi/problemset/',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'competitive', 'problems'],
      },
      {
        id: 'visualgo',
        title: 'VisuAlgo',
        description: 'Visualize data structures and algorithms step by step. Great for building mental models.',
        url: 'https://visualgo.net',
        type: 'tool',
        free: true,
        mustKnow: false,
        tags: ['visualization', 'learning'],
      },
      {
        id: 'cp-algorithms',
        title: 'CP-Algorithms',
        description: 'Translation of the famous e-maxx blog. Deep theoretical explanations with proofs.',
        url: 'https://cp-algorithms.com',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'theory', 'competitive'],
      },
      {
        id: 'hackerrank',
        title: 'HackerRank',
        description: 'Skill-based challenges with certifications. Many companies use it for OAs.',
        url: 'https://www.hackerrank.com',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'oa', 'certification'],
      },
      {
        id: 'codechef',
        title: 'CodeChef',
        description: 'Indian competitive programming platform. Great for ratings and contest practice.',
        url: 'https://www.codechef.com',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['competitive', 'contests', 'india'],
      },
      {
        id: 'codeforces',
        title: 'Codeforces',
        description: 'The most competitive CP platform globally. Rated contests every week.',
        url: 'https://codeforces.com',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['competitive', 'contests', 'advanced'],
      },
      {
        id: 'lc-patterns',
        title: 'LeetCode Patterns by Sean Prashad',
        description: 'Problems grouped by coding patterns (sliding window, two pointer, etc.). Pattern-first approach.',
        url: 'https://seanprashad.com/leetcode-patterns/',
        type: 'sheet',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'patterns', 'sheet'],
      },
    ],
  },

  // ─── SYSTEM DESIGN ─────────────────────────────────────────────────────────
  {
    id: 'system-design',
    label: 'System Design (HLD)',
    emoji: '🏗️',
    color: '#6366f1',
    resources: [
      {
        id: 'system-design-primer',
        title: 'System Design Primer',
        description: 'The most comprehensive free system design resource on GitHub. 265k+ stars.',
        url: 'https://github.com/donnemartin/system-design-primer',
        type: 'github',
        free: true,
        mustKnow: true,
        tags: ['system-design', 'hld', 'comprehensive'],
      },
      {
        id: 'bytebytego-newsletter',
        title: 'ByteByteGo Newsletter',
        description: 'Weekly system design breakdowns with beautiful diagrams. Free tier is excellent.',
        url: 'https://blog.bytebytego.com',
        type: 'blog',
        free: true,
        mustKnow: true,
        tags: ['system-design', 'newsletter', 'visual'],
      },
      {
        id: 'high-scalability',
        title: 'High Scalability Blog',
        description: 'Real-world case studies of how top companies (Netflix, Twitter) scaled their systems.',
        url: 'http://highscalability.com',
        type: 'blog',
        free: true,
        mustKnow: false,
        tags: ['system-design', 'real-world', 'case-studies'],
      },
      {
        id: 'martin-fowler',
        title: "Martin Fowler's Blog",
        description: 'Deep dives into architecture patterns, microservices, and software design principles.',
        url: 'https://martinfowler.com',
        type: 'blog',
        free: true,
        mustKnow: false,
        tags: ['architecture', 'patterns', 'microservices'],
      },
      {
        id: 'awesome-system-design',
        title: 'ashishps1/awesome-system-design-resources',
        description: 'Curated GitHub list of system design resources, papers, and references.',
        url: 'https://github.com/ashishps1/awesome-system-design-resources',
        type: 'github',
        free: true,
        mustKnow: true,
        tags: ['system-design', 'curated', 'github'],
      },
      {
        id: 'system-design-interview-repo',
        title: 'karanpratapsingh/system-design',
        description: 'Open-source system design guide with diagrams. Free alternative to the paid book.',
        url: 'https://github.com/karanpratapsingh/system-design',
        type: 'github',
        free: true,
        mustKnow: false,
        tags: ['system-design', 'guide', 'diagrams'],
      },
      {
        id: 'engineering-blogs',
        title: 'Engineering Blogs Aggregator',
        description: 'Aggregated engineering blogs from Google, Amazon, Netflix, Uber, Airbnb and more.',
        url: 'https://github.com/kilimchoi/engineering-blogs',
        type: 'github',
        free: true,
        mustKnow: false,
        tags: ['system-design', 'real-world', 'company-blogs'],
      },
      {
        id: 'aws-architecture',
        title: 'AWS Architecture Center',
        description: 'Official AWS reference architectures and best practices. Great for cloud system design.',
        url: 'https://aws.amazon.com/architecture/',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['system-design', 'cloud', 'aws'],
      },
    ],
  },

  // ─── LOW LEVEL DESIGN ──────────────────────────────────────────────────────
  {
    id: 'lld',
    label: 'Low Level Design (LLD)',
    emoji: '🧩',
    color: '#8b5cf6',
    resources: [
      {
        id: 'refactoring-guru',
        title: 'Refactoring Guru — Design Patterns',
        description: 'Best free resource for design patterns with real code examples and visual diagrams.',
        url: 'https://refactoring.guru/design-patterns',
        type: 'website',
        free: true,
        mustKnow: true,
        tags: ['lld', 'design-patterns', 'oop'],
      },
      {
        id: 'lld-github',
        title: 'ashishps1/awesome-low-level-design',
        description: 'GitHub repo with LLD questions (Parking Lot, Snake Game, Chess) and solutions.',
        url: 'https://github.com/ashishps1/awesome-low-level-design',
        type: 'github',
        free: true,
        mustKnow: true,
        tags: ['lld', 'problems', 'solutions'],
      },
      {
        id: 'solid-principles',
        title: 'SOLID Principles Explained — Baeldung',
        description: 'Clear explanation of SOLID with Java/Python examples and anti-patterns.',
        url: 'https://www.baeldung.com/solid-principles',
        type: 'article',
        free: true,
        mustKnow: true,
        tags: ['lld', 'solid', 'oop'],
      },
      {
        id: 'oodesign',
        title: 'OODesign.com',
        description: 'Classic GoF design patterns explained with UML diagrams. Quick reference.',
        url: 'https://www.oodesign.com',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['lld', 'design-patterns', 'gof'],
      },
      {
        id: 'uml-diagrams',
        title: 'UML Diagrams Guide',
        description: 'Learn to draw class diagrams, sequence diagrams for LLD interviews.',
        url: 'https://www.uml-diagrams.org',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['lld', 'uml', 'diagrams'],
      },
    ],
  },

  // ─── YOUTUBE CHANNELS ──────────────────────────────────────────────────────
  {
    id: 'youtube',
    label: 'YouTube Channels',
    emoji: '▶️',
    color: '#ec4899',
    resources: [
      {
        id: 'take-u-forward',
        title: 'take U forward (Striver)',
        description: 'Best DSA course on YouTube in Hindi/English. SDE sheet explained end-to-end.',
        url: 'https://www.youtube.com/@takeUforward',
        type: 'youtube',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'hindi', 'youtube', 'beginner-friendly'],
      },
      {
        id: 'neetcode-yt',
        title: 'NeetCode',
        description: 'Clean, concise Python solutions to every LeetCode problem you need.',
        url: 'https://www.youtube.com/@NeetCode',
        type: 'youtube',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'english', 'youtube'],
      },
      {
        id: 'tech-dummies',
        title: 'Tech Dummies Narendra L',
        description: 'Great system design tutorials for Indian SWEs. HLD explained clearly.',
        url: 'https://www.youtube.com/@TechDummiesNarendraL',
        type: 'youtube',
        free: true,
        mustKnow: false,
        tags: ['system-design', 'youtube', 'hindi'],
      },
      {
        id: 'coder-army',
        title: 'Coder Army',
        description: 'DSA in C++ by Rohit Negi. Very popular among Indian CS students.',
        url: 'https://www.youtube.com/@CoderArmy9',
        type: 'youtube',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'cpp', 'youtube'],
      },
      {
        id: 'gaurav-sen',
        title: 'Gaurav Sen',
        description: 'System design concepts explained brilliantly. A must-follow for senior roles.',
        url: 'https://www.youtube.com/@gkcs',
        type: 'youtube',
        free: true,
        mustKnow: true,
        tags: ['system-design', 'youtube', 'advanced'],
      },
      {
        id: 'apna-college',
        title: 'Apna College',
        description: 'DSA in Java by Shradha & Aman. Very beginner-friendly, great for starters.',
        url: 'https://www.youtube.com/@ApnaCollegeOfficial',
        type: 'youtube',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'java', 'hindi', 'beginner'],
      },
      {
        id: 'aditya-verma',
        title: 'Aditya Verma',
        description: 'Best DP and Recursion playlist on YouTube. His DP series is legendary.',
        url: 'https://www.youtube.com/@adityaverma7555',
        type: 'youtube',
        free: true,
        mustKnow: true,
        tags: ['dsa', 'dp', 'recursion', 'youtube'],
      },
      {
        id: 'love-babbar',
        title: 'Love Babbar',
        description: 'DSA course and 450 questions sheet. Popular among Indian CS students.',
        url: 'https://www.youtube.com/@LoveBabbar1',
        type: 'youtube',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'hindi', 'youtube'],
      },
      {
        id: 'back-to-back-swe',
        title: 'Back To Back SWE',
        description: 'In-depth walkthroughs of hard LeetCode problems. Great for understanding intuition.',
        url: 'https://www.youtube.com/@BackToBackSWE',
        type: 'youtube',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'english', 'youtube', 'intuition'],
      },
      {
        id: 'jenny-lectures',
        title: "Jenny's Lectures CS IT",
        description: 'Data structures and algorithms fundamentals explained from scratch.',
        url: 'https://www.youtube.com/@JennyslecturesCSIT',
        type: 'youtube',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'fundamentals', 'youtube'],
      },
      {
        id: 'code-with-harry',
        title: 'CodeWithHarry',
        description: 'Hindi programming tutorials. Great for learning new languages quickly.',
        url: 'https://www.youtube.com/@CodeWithHarry',
        type: 'youtube',
        free: true,
        mustKnow: false,
        tags: ['programming', 'hindi', 'youtube'],
      },
      {
        id: 'errichto',
        title: 'Errichto (Algorithms)',
        description: 'Expert competitive programmer explains hard algorithms. Great for CP aspirants.',
        url: 'https://www.youtube.com/@Errichto',
        type: 'youtube',
        free: true,
        mustKnow: false,
        tags: ['competitive', 'algorithms', 'advanced'],
      },
    ],
  },

  // ─── INTERVIEW PREP ────────────────────────────────────────────────────────
  {
    id: 'interview-prep',
    label: 'Interview Prep',
    emoji: '🎯',
    color: '#f59e0b',
    resources: [
      {
        id: 'pramp',
        title: 'Pramp',
        description: 'Free peer-to-peer mock interviews. Practice with real engineers worldwide.',
        url: 'https://www.pramp.com',
        type: 'platform',
        free: true,
        mustKnow: true,
        tags: ['mock-interview', 'practice', 'free'],
      },
      {
        id: 'interviewing-io',
        title: 'interviewing.io',
        description: 'Practice technical interviews anonymously with engineers from top companies.',
        url: 'https://interviewing.io',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['mock-interview', 'anonymous', 'practice'],
      },
      {
        id: 'levels-fyi',
        title: 'levels.fyi',
        description: 'See real salary data for product companies. Know your worth before negotiating.',
        url: 'https://www.levels.fyi',
        type: 'tool',
        free: true,
        mustKnow: true,
        tags: ['salary', 'research', 'negotiation'],
      },
      {
        id: 'blind',
        title: 'Blind (App)',
        description: 'Anonymous forum where engineers discuss companies, offers, and interview experiences.',
        url: 'https://www.teamblind.com',
        type: 'community',
        free: true,
        mustKnow: false,
        tags: ['community', 'salaries', 'interviews'],
      },
      {
        id: 'interview-bit',
        title: 'InterviewBit',
        description: 'Structured DSA + CS fundamentals prep platform. Very popular in India.',
        url: 'https://www.interviewbit.com',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['dsa', 'cs-fundamentals', 'india'],
      },
      {
        id: 'amazon-lp',
        title: 'Amazon Leadership Principles Guide',
        description: 'Comprehensive STAR-method answers for all 16 Amazon Leadership Principles.',
        url: 'https://www.amazon.jobs/content/en/our-workplace/leadership-principles',
        type: 'guide',
        free: true,
        mustKnow: true,
        tags: ['amazon', 'behavioral', 'lp', 'star'],
      },
      {
        id: 'gfg-experiences',
        title: 'GFG Interview Experiences',
        description: 'Thousands of real interview experiences at Amazon, Google, Flipkart, and more.',
        url: 'https://www.geeksforgeeks.org/company-interview-corner/',
        type: 'community',
        free: true,
        mustKnow: true,
        tags: ['interview', 'experience', 'real-stories', 'india'],
      },
      {
        id: 'lc-discuss',
        title: 'LeetCode Discuss',
        description: 'Company-specific interview questions shared by candidates after their interviews.',
        url: 'https://leetcode.com/discuss/interview-experience',
        type: 'community',
        free: true,
        mustKnow: true,
        tags: ['interview', 'experience', 'company-specific'],
      },
      {
        id: 'glassdoor',
        title: 'Glassdoor Interview Reviews',
        description: 'Read exactly what interview questions companies asked other candidates.',
        url: 'https://www.glassdoor.com/Interview/index.htm',
        type: 'community',
        free: true,
        mustKnow: false,
        tags: ['interview', 'experience', 'company'],
      },
    ],
  },

  // ─── CS FUNDAMENTALS ───────────────────────────────────────────────────────
  {
    id: 'cs-fundamentals',
    label: 'CS Fundamentals',
    emoji: '🖥️',
    color: '#06b6d4',
    resources: [
      {
        id: 'os-concepts',
        title: 'Operating Systems — GATE Smashers (YouTube)',
        description: 'Complete OS playlist covering processes, threads, scheduling, memory. GATE-level depth.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p',
        type: 'youtube',
        free: true,
        mustKnow: true,
        tags: ['os', 'fundamentals', 'hindi'],
      },
      {
        id: 'dbms-neso',
        title: 'DBMS — Neso Academy (YouTube)',
        description: 'Complete DBMS playlist from basics to transactions and normalization.',
        url: 'https://www.youtube.com/playlist?list=PLBlnK6fEyqRi_CUQ-FbjgCGBXTo3HnSTt',
        type: 'youtube',
        free: true,
        mustKnow: true,
        tags: ['dbms', 'fundamentals', 'sql'],
      },
      {
        id: 'cn-gate',
        title: 'Computer Networks — GATE Smashers (YouTube)',
        description: 'TCP/IP, DNS, HTTP, routing protocols explained for interviews.',
        url: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiFAN6I8CuViBuCdJgiOkT2Y',
        type: 'youtube',
        free: true,
        mustKnow: true,
        tags: ['networking', 'fundamentals', 'tcp-ip'],
      },
      {
        id: 'interviewbit-cs',
        title: 'InterviewBit — CS Fundamentals',
        description: 'Quick-revision notes for OS, DBMS, CN, OOP — perfect before interviews.',
        url: 'https://www.interviewbit.com/technical-interview-questions/',
        type: 'platform',
        free: true,
        mustKnow: true,
        tags: ['os', 'dbms', 'cn', 'oop', 'revision'],
      },
      {
        id: 'sqlzoo',
        title: 'SQLZoo',
        description: 'Interactive SQL practice. Master JOINs, subqueries, and aggregations hands-on.',
        url: 'https://sqlzoo.net',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['sql', 'dbms', 'practice'],
      },
      {
        id: 'mode-sql',
        title: 'Mode SQL Tutorial',
        description: 'From basic SELECT to advanced window functions. Great for data-heavy interviews.',
        url: 'https://mode.com/sql-tutorial/',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['sql', 'advanced', 'analytics'],
      },
      {
        id: 'linux-command-line',
        title: 'The Linux Command Line (Free Book)',
        description: 'Essential Linux CLI skills for backend SWE interviews. Shell scripting included.',
        url: 'https://linuxcommand.org/tlcl.php',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['linux', 'shell', 'backend'],
      },
    ],
  },

  // ─── FREE BOOKS & COURSES ──────────────────────────────────────────────────
  {
    id: 'books-courses',
    label: 'Free Books & Courses',
    emoji: '📚',
    color: '#f97316',
    resources: [
      {
        id: 'mit-ocw-6006',
        title: 'MIT 6.006 — Introduction to Algorithms',
        description: 'MIT\'s legendary algorithms course. Free lecture videos, notes, and problem sets.',
        url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['algorithms', 'course', 'academic'],
      },
      {
        id: 'algorithms-book',
        title: 'Algorithms by Jeff Erickson (Free PDF)',
        description: 'University textbook on algorithms. Free to download legally from the author.',
        url: 'https://jeffe.cs.illinois.edu/teaching/algorithms/',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['algorithms', 'book', 'theory'],
      },
      {
        id: 'cs50',
        title: 'Harvard CS50 — Introduction to CS',
        description: 'The best intro CS course ever made. Free on edX. Covers C, Python, SQL, and web.',
        url: 'https://cs50.harvard.edu/x/',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['fundamentals', 'course', 'beginner'],
      },
      {
        id: 'learn-git',
        title: 'Pro Git Book (Free)',
        description: 'Official free Git book by Scott Chacon. Master Git for professional development.',
        url: 'https://git-scm.com/book/en/v2',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['git', 'tools', 'professional'],
      },
      {
        id: 'ddia',
        title: 'Designing Data-Intensive Applications (DDIA)',
        description: 'The bible of distributed systems. Complex but worth it for system design mastery.',
        url: 'https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/',
        type: 'website',
        free: false,
        mustKnow: false,
        tags: ['system-design', 'distributed', 'advanced'],
      },
      {
        id: 'the-algorithm-design-manual',
        title: 'Algorithm Design Manual (Skiena)',
        description: 'Practical, less theoretical than CLRS. Great "war stories" of real problem solving.',
        url: 'https://www.algorist.com',
        type: 'website',
        free: false,
        mustKnow: false,
        tags: ['algorithms', 'book', 'practical'],
      },
      {
        id: 'freeCodeCamp',
        title: 'freeCodeCamp',
        description: 'Free full-stack curriculum with certifications. JavaScript, Python, and more.',
        url: 'https://www.freecodecamp.org',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['web', 'programming', 'course', 'certification'],
      },
    ],
  },

  // ─── COMMUNITIES ───────────────────────────────────────────────────────────
  {
    id: 'communities',
    label: 'Communities & Forums',
    emoji: '🤝',
    color: '#a78bfa',
    resources: [
      {
        id: 'reddit-cscareer',
        title: 'r/cscareerquestions',
        description: '2M+ engineers discussing job search, salary, interviews, and tech careers.',
        url: 'https://www.reddit.com/r/cscareerquestions/',
        type: 'community',
        free: true,
        mustKnow: true,
        tags: ['community', 'career', 'advice'],
      },
      {
        id: 'reddit-india-careers',
        title: 'r/developersIndia',
        description: 'India-specific discussions on job switching, salaries, and interview tips.',
        url: 'https://www.reddit.com/r/developersIndia/',
        type: 'community',
        free: true,
        mustKnow: true,
        tags: ['community', 'india', 'career'],
      },
      {
        id: 'discord-cs',
        title: 'CS Career Hub (Discord)',
        description: 'Active Discord server for CS job seekers. Resume reviews, referrals, and resources.',
        url: 'https://discord.gg/cscareers',
        type: 'community',
        free: true,
        mustKnow: false,
        tags: ['community', 'discord', 'career'],
      },
      {
        id: 'discord-neetcode',
        title: 'NeetCode Discord',
        description: 'NeetCode\'s official Discord for discussing LeetCode problems and interview prep.',
        url: 'https://discord.gg/neetcode',
        type: 'community',
        free: true,
        mustKnow: false,
        tags: ['community', 'discord', 'dsa'],
      },
      {
        id: 'hashnode',
        title: 'Hashnode',
        description: 'Developer blogging platform. Read how others solved problems and built projects.',
        url: 'https://hashnode.com',
        type: 'community',
        free: true,
        mustKnow: false,
        tags: ['community', 'blogs', 'learning'],
      },
      {
        id: 'dev-to',
        title: 'dev.to',
        description: 'Community of software developers sharing tutorials, articles, and discussions.',
        url: 'https://dev.to',
        type: 'community',
        free: true,
        mustKnow: false,
        tags: ['community', 'articles', 'tutorials'],
      },
    ],
  },

  // ─── RESUME & LINKEDIN ─────────────────────────────────────────────────────
  {
    id: 'resume',
    label: 'Resume & LinkedIn',
    emoji: '📄',
    color: '#34d399',
    resources: [
      {
        id: 'jake-resume',
        title: "Jake's Resume Template",
        description: 'The most ATS-friendly LaTeX resume template. Used by thousands of SWEs worldwide.',
        url: 'https://www.overleaf.com/latex/templates/jakes-resume/syzfjbzwjncs',
        type: 'template',
        free: true,
        mustKnow: true,
        tags: ['resume', 'template', 'ats', 'latex'],
      },
      {
        id: 'resume-worded',
        title: 'Resume Worded',
        description: 'Free AI-powered resume checker. Get instant feedback and score against ATS.',
        url: 'https://resumeworded.com',
        type: 'tool',
        free: true,
        mustKnow: false,
        tags: ['resume', 'feedback', 'ai', 'ats'],
      },
      {
        id: 'rxresu',
        title: 'RxResume (Free Resume Builder)',
        description: 'Open-source, privacy-friendly resume builder. Clean templates, no sign-up required.',
        url: 'https://rxresu.me',
        type: 'tool',
        free: true,
        mustKnow: false,
        tags: ['resume', 'builder', 'free'],
      },
      {
        id: 'linkedin-tips',
        title: 'LinkedIn Profile Optimization Guide',
        description: 'Official LinkedIn guide on getting found by recruiters. Keyword optimization tips.',
        url: 'https://linkedin.com/help/linkedin/answer/a554351',
        type: 'guide',
        free: true,
        mustKnow: false,
        tags: ['linkedin', 'profile', 'recruiter'],
      },
      {
        id: 'github-profile',
        title: 'GitHub Profile README Generator',
        description: 'Make your GitHub profile stand out with a custom README. Recruiters check GitHub.',
        url: 'https://rahuldkjain.github.io/gh-profile-readme-generator/',
        type: 'tool',
        free: true,
        mustKnow: false,
        tags: ['github', 'profile', 'portfolio'],
      },
      {
        id: 'cold-email',
        title: 'Cold Email Templates for Referrals',
        description: 'Templates for reaching out to employees at target companies for referrals.',
        url: 'https://www.reddit.com/r/cscareerquestions/comments/55ysbs/i_got_a_job_at_a_fang_company_here_is_my_strategy/',
        type: 'article',
        free: true,
        mustKnow: false,
        tags: ['referral', 'networking', 'outreach'],
      },
    ],
  },

  // ─── COMPETITIVE PROGRAMMING ───────────────────────────────────────────────
  {
    id: 'competitive',
    label: 'Competitive Programming',
    emoji: '🏆',
    color: '#fbbf24',
    resources: [
      {
        id: 'usaco-guide',
        title: 'USACO Guide',
        description: 'Best structured CP curriculum. Covers Bronze to Platinum level topics with problems.',
        url: 'https://usaco.guide',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['competitive', 'structured', 'guide'],
      },
      {
        id: 'cp-handbook',
        title: 'Competitive Programmer\'s Handbook (Free PDF)',
        description: 'Comprehensive free e-book by Antti Laaksonen. The CP Bible.',
        url: 'https://cses.fi/book/book.pdf',
        type: 'website',
        free: true,
        mustKnow: false,
        tags: ['competitive', 'book', 'algorithms'],
      },
      {
        id: 'atcoder',
        title: 'AtCoder',
        description: 'Japanese CP platform. Great problem quality, especially for DP and math.',
        url: 'https://atcoder.jp',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['competitive', 'platform', 'advanced'],
      },
      {
        id: 'projecteuler',
        title: 'Project Euler',
        description: '800+ math-focused programming problems. Great for number theory and bit manipulation.',
        url: 'https://projecteuler.net',
        type: 'platform',
        free: true,
        mustKnow: false,
        tags: ['competitive', 'math', 'problems'],
      },
    ],
  },

  // ─── TOOLS & PRODUCTIVITY ──────────────────────────────────────────────────
  {
    id: 'tools',
    label: 'Dev Tools & Productivity',
    emoji: '🛠️',
    color: '#64748b',
    resources: [
      {
        id: 'excalidraw',
        title: 'Excalidraw',
        description: 'Free whiteboard for drawing system design diagrams during interviews.',
        url: 'https://excalidraw.com',
        type: 'tool',
        free: true,
        mustKnow: true,
        tags: ['tool', 'diagrams', 'whiteboard'],
      },
      {
        id: 'notion-template',
        title: 'Notion Study Tracker Templates',
        description: 'Free Notion templates for tracking LeetCode progress and study plans.',
        url: 'https://www.notion.so/templates/category/engineering',
        type: 'tool',
        free: true,
        mustKnow: false,
        tags: ['tool', 'productivity', 'tracking'],
      },
      {
        id: 'regex101',
        title: 'Regex101',
        description: 'Test and debug regular expressions live. Invaluable for string manipulation problems.',
        url: 'https://regex101.com',
        type: 'tool',
        free: true,
        mustKnow: false,
        tags: ['tool', 'regex', 'strings'],
      },
      {
        id: 'bigocheatsheet',
        title: 'Big-O Cheat Sheet',
        description: 'Quick reference for time and space complexity of common algorithms and data structures.',
        url: 'https://www.bigocheatsheet.com',
        type: 'tool',
        free: true,
        mustKnow: true,
        tags: ['tool', 'complexity', 'reference'],
      },
      {
        id: 'python-tutor',
        title: 'Python Tutor',
        description: 'Visualize code execution step by step. Great for debugging recursion and pointers.',
        url: 'https://pythontutor.com',
        type: 'tool',
        free: true,
        mustKnow: false,
        tags: ['tool', 'visualization', 'debugging'],
      },
      {
        id: 'github-copilot-student',
        title: 'GitHub Student Developer Pack',
        description: 'Free access to GitHub Copilot, Namecheap domains, and 100+ tools if you\'re a student.',
        url: 'https://education.github.com/pack',
        type: 'tool',
        free: true,
        mustKnow: true,
        tags: ['tool', 'student', 'free-perks'],
      },
    ],
  },
];

// ─── FEATURED VIDEOS ─────────────────────────────────────────────────────────
// These are embedded YouTube videos playable inside the app.
// If a video doesn't load, update the videoId in this file.
export const FEATURED_VIDEOS = [
  {
    id: 'vid-dp-fcc',
    videoId: 'oBt53YbR9Kk',
    title: 'Dynamic Programming — Learn to Solve Algorithmic Problems',
    channel: 'freeCodeCamp.org',
    duration: '5h 13m',
    description: 'Complete dynamic programming course covering memoization, tabulation, and classic DP patterns used in FAANG interviews.',
    tags: ['dp', 'algorithms', 'faang'],
    mustKnow: true,
  },
  {
    id: 'vid-graph-fcc',
    videoId: 'tWVWeAqZ0WU',
    title: 'Graph Algorithms for Technical Interviews',
    channel: 'freeCodeCamp.org',
    duration: '2h 14m',
    description: 'BFS, DFS, Dijkstra, and more. All graph algorithms you need for coding interviews explained with visualizations.',
    tags: ['graphs', 'bfs', 'dfs', 'faang'],
    mustKnow: true,
  },
  {
    id: 'vid-dsa-full',
    videoId: 'RBSGKlAvoiM',
    title: 'Data Structures Easy to Advanced — Full Course',
    channel: 'freeCodeCamp.org',
    duration: '8h 2m',
    description: 'Covers arrays, linked lists, trees, heaps, hash tables, and graphs from scratch. Great for building strong fundamentals.',
    tags: ['dsa', 'fundamentals', 'beginner'],
    mustKnow: false,
  },
  {
    id: 'vid-dp-striver',
    videoId: 'tyB0ztf0DNY',
    title: 'Dynamic Programming Playlist — Striver',
    channel: 'take U forward',
    duration: 'Playlist',
    description: 'Striver\'s complete DP series in Hindi/English. Most comprehensive DP coverage for Indian SWE interviews.',
    tags: ['dp', 'hindi', 'striver'],
    mustKnow: true,
  },
  {
    id: 'vid-sd-basics',
    videoId: 'quLrc3PbuIw',
    title: 'System Design Concepts — Full Course',
    channel: 'freeCodeCamp.org',
    duration: '4h 50m',
    description: 'CAP theorem, consistent hashing, load balancing, caching, databases, and more — everything for senior SWE interviews.',
    tags: ['system-design', 'hld', 'senior'],
    mustKnow: true,
  },
  {
    id: 'vid-lld-patterns',
    videoId: 'v9ejT8FO-3I',
    title: 'Design Patterns in Object Oriented Programming',
    channel: 'Christopher Okhravi',
    duration: 'Playlist',
    description: 'In-depth series on GoF design patterns with real-world examples. Best for LLD interview preparation.',
    tags: ['lld', 'design-patterns', 'oop'],
    mustKnow: false,
  },
  {
    id: 'vid-recursion',
    videoId: 'ngCos392W4w',
    title: 'Recursion in Programming — Full Course',
    channel: 'freeCodeCamp.org',
    duration: '2h 30m',
    description: 'Master recursion from the ground up. Covers call stack, base cases, tree recursion, backtracking and more.',
    tags: ['recursion', 'algorithms', 'beginner'],
    mustKnow: false,
  },
  {
    id: 'vid-sql-full',
    videoId: 'HXV3zeQKqGY',
    title: 'SQL Tutorial — Full Database Course',
    channel: 'freeCodeCamp.org',
    duration: '4h 20m',
    description: 'Complete SQL from basics to advanced queries, JOINs, stored procedures. Essential for DBMS interview rounds.',
    tags: ['sql', 'dbms', 'backend'],
    mustKnow: false,
  },
];

export const RESOURCE_TYPES = {
  platform:  { label: 'Platform',    color: '#10b981' },
  github:    { label: 'GitHub',      color: '#6366f1' },
  youtube:   { label: 'YouTube',     color: '#ec4899' },
  blog:      { label: 'Blog',        color: '#f59e0b' },
  sheet:     { label: 'Sheet',       color: '#8b5cf6' },
  tool:      { label: 'Tool',        color: '#06b6d4' },
  community: { label: 'Community',   color: '#f97316' },
  template:  { label: 'Template',    color: '#a78bfa' },
  article:   { label: 'Article',     color: '#94a3b8' },
  guide:     { label: 'Guide',       color: '#fbbf24' },
  website:   { label: 'Website',     color: '#34d399' },
};
