// ─── CAREER ROADMAPS — Structured paths from service to product ───────────────

export const ROADMAPS = [
  {
    id: 'sde2-product',
    label: 'SDE-2 at Product Company',
    emoji: '🚀',
    color: '#10b981',
    description: 'The complete path to crack SDE-2 at Amazon, Flipkart, Swiggy, or Zomato',
    duration: '4–6 months',
    premium: false,
    phases: [
      {
        id: 'foundation',
        label: 'Phase 1 — Foundation',
        weeks: '1–4',
        color: '#10b981',
        steps: [
          { id: 'setup-leetcode', label: 'Create LeetCode account, solve 5 easy problems', done: false },
          { id: 'learn-complexity', label: 'Master Big-O analysis (time & space)', done: false },
          { id: 'arrays-basics', label: 'Complete Arrays & Strings section in DSA tracker', done: false },
          { id: 'first-20', label: 'Solve first 20 LeetCode Easy problems', done: false },
          { id: 'cs-fundamentals', label: 'Revise OS basics: processes, threads, memory', done: false },
          { id: 'git-basics', label: 'Get comfortable with Git: branch, merge, rebase', done: false },
        ],
      },
      {
        id: 'core-dsa',
        label: 'Phase 2 — Core DSA',
        weeks: '5–10',
        color: '#6366f1',
        steps: [
          { id: 'binary-search-done', label: 'Complete Binary Search section (all 7 topics)', done: false },
          { id: 'linked-list-done', label: 'Complete Linked Lists section', done: false },
          { id: 'trees-done', label: 'Complete Trees & BST section', done: false },
          { id: 'solve-50', label: 'Reach 50 LeetCode problems solved', done: false },
          { id: 'stack-queue-done', label: 'Complete Stack, Queue & Heap section', done: false },
          { id: 'hashing-done', label: 'Complete Hashing & Sorting section', done: false },
          { id: 'mock-interviews', label: 'Do 5 mock interviews on Pramp / interviewing.io', done: false },
        ],
      },
      {
        id: 'advanced-dsa',
        label: 'Phase 3 — Advanced DSA',
        weeks: '11–16',
        color: '#8b5cf6',
        steps: [
          { id: 'graphs-done', label: 'Complete Graphs section', done: false },
          { id: 'dp-done', label: 'Complete Dynamic Programming section', done: false },
          { id: 'backtracking-done', label: 'Complete Backtracking section', done: false },
          { id: 'solve-150', label: 'Reach 150 LeetCode problems solved', done: false },
          { id: 'contest-5', label: 'Participate in 5 LeetCode weekly contests', done: false },
          { id: 'company-wise', label: 'Solve Amazon/Flipkart tagged problems on LeetCode', done: false },
        ],
      },
      {
        id: 'interviews',
        label: 'Phase 4 — Interview Readiness',
        weeks: '17–20',
        color: '#f59e0b',
        steps: [
          { id: 'resume-update', label: 'Update resume with impact numbers (not just duties)', done: false },
          { id: 'system-design-basics', label: 'Learn System Design basics (HLD)', done: false },
          { id: 'behavioral-prep', label: 'Prepare STAR-format stories for 10 behavioral questions', done: false },
          { id: 'apply-10', label: 'Apply to 10 companies via LinkedIn / Naukri', done: false },
          { id: 'referrals', label: 'Get 3+ referrals from alumni/connections at product companies', done: false },
          { id: 'offer', label: '🎉 Land the offer!', done: false },
        ],
      },
    ],
  },
  {
    id: 'frontend-specialist',
    label: 'Frontend Engineer Path',
    emoji: '🎨',
    color: '#ec4899',
    description: 'Become a frontend specialist — React, performance, and system design',
    duration: '3–5 months',
    premium: false,
    phases: [
      {
        id: 'js-mastery',
        label: 'Phase 1 — JavaScript Mastery',
        weeks: '1–4',
        color: '#ec4899',
        steps: [
          { id: 'js-closures', label: 'Deeply understand closures, scope, hoisting', done: false },
          { id: 'js-async', label: 'Master Promises, async/await, event loop', done: false },
          { id: 'js-prototype', label: 'Understand prototypal inheritance & this keyword', done: false },
          { id: 'es6-plus', label: 'Destructuring, spread, modules, optional chaining', done: false },
          { id: 'dom-apis', label: 'Practice DOM manipulation without frameworks', done: false },
        ],
      },
      {
        id: 'react-advanced',
        label: 'Phase 2 — React Deep Dive',
        weeks: '5–9',
        color: '#6366f1',
        steps: [
          { id: 'react-hooks', label: 'Master all hooks: useState, useEffect, useRef, useMemo, useCallback', done: false },
          { id: 'react-patterns', label: 'Learn compound components, render props, HOC patterns', done: false },
          { id: 'state-management', label: 'Learn Redux Toolkit or Zustand for state management', done: false },
          { id: 'react-query', label: 'Use TanStack Query for data fetching & caching', done: false },
          { id: 'build-3-projects', label: 'Build 3 portfolio projects (not todo apps!)', done: false },
        ],
      },
      {
        id: 'performance',
        label: 'Phase 3 — Performance & Browser',
        weeks: '10–14',
        color: '#10b981',
        steps: [
          { id: 'core-web-vitals', label: 'Learn Core Web Vitals: LCP, CLS, FID/INP', done: false },
          { id: 'lazy-loading', label: 'Implement lazy loading, code splitting, tree shaking', done: false },
          { id: 'browser-rendering', label: 'Understand critical rendering path', done: false },
          { id: 'lighthouse', label: 'Get a Lighthouse score of 90+ on your projects', done: false },
          { id: 'typescript', label: 'Add TypeScript to at least one project', done: false },
        ],
      },
      {
        id: 'fe-interviews',
        label: 'Phase 4 — Frontend Interview Prep',
        weeks: '15–18',
        color: '#f59e0b',
        steps: [
          { id: 'machine-coding', label: 'Practice 20 machine coding problems', done: false },
          { id: 'fe-system-design', label: 'Learn frontend system design: component libraries, micro-frontends', done: false },
          { id: 'lld-practice', label: 'Design a Typeahead, Infinite Scroll, Drag-Drop component', done: false },
          { id: 'dsa-frontend', label: 'Solve 80+ LeetCode problems (JS focus)', done: false },
          { id: 'fe-offer', label: '🎉 Get that frontend role!', done: false },
        ],
      },
    ],
  },
  {
    id: 'backend-specialist',
    label: 'Backend Engineer Path',
    emoji: '⚙️',
    color: '#6366f1',
    description: 'Build robust backend systems — APIs, databases, and microservices',
    duration: '4–6 months',
    premium: false,
    phases: [
      {
        id: 'backend-foundation',
        label: 'Phase 1 — Backend Foundation',
        weeks: '1–4',
        color: '#6366f1',
        steps: [
          { id: 'http-rest', label: 'Master HTTP methods, status codes, REST principles', done: false },
          { id: 'node-or-java', label: 'Pick Node.js or Java Spring Boot and get comfortable', done: false },
          { id: 'build-crud-api', label: 'Build a CRUD REST API with authentication', done: false },
          { id: 'sql-basics', label: 'Write complex SQL: JOINs, subqueries, indexes, EXPLAIN', done: false },
          { id: 'auth-jwt', label: 'Implement JWT auth with refresh tokens', done: false },
        ],
      },
      {
        id: 'databases',
        label: 'Phase 2 — Databases & Caching',
        weeks: '5–9',
        color: '#10b981',
        steps: [
          { id: 'sql-advanced', label: 'Learn transactions, ACID, isolation levels', done: false },
          { id: 'nosql', label: 'Understand MongoDB or DynamoDB for document storage', done: false },
          { id: 'redis', label: 'Use Redis for caching, rate limiting, sessions', done: false },
          { id: 'db-design', label: 'Design 3 real-world database schemas', done: false },
          { id: 'orm', label: 'Use Prisma, Hibernate, or TypeORM — understand N+1 problem', done: false },
        ],
      },
      {
        id: 'system-thinking',
        label: 'Phase 3 — System Thinking',
        weeks: '10–16',
        color: '#8b5cf6',
        steps: [
          { id: 'microservices', label: 'Understand microservices vs monolith trade-offs', done: false },
          { id: 'message-queues', label: 'Learn Kafka or RabbitMQ for async processing', done: false },
          { id: 'docker', label: 'Dockerize your applications', done: false },
          { id: 'monitoring', label: 'Set up logging and monitoring (Prometheus / Grafana basics)', done: false },
          { id: 'system-design-30', label: 'Study 30 system design questions', done: false },
        ],
      },
      {
        id: 'be-interviews',
        label: 'Phase 4 — Interview Prep',
        weeks: '17–20',
        color: '#f59e0b',
        steps: [
          { id: 'dsa-150-be', label: 'Solve 150+ LeetCode problems (focus on graphs, DP)', done: false },
          { id: 'lld-be', label: 'Design: Parking Lot, Cab Booking, Rate Limiter', done: false },
          { id: 'hld-be', label: 'Design: URL Shortener, Twitter Feed, Uber', done: false },
          { id: 'be-offer', label: '🎉 Land your backend role!', done: false },
        ],
      },
    ],
  },
  {
    id: 'system-design',
    label: 'System Design Mastery',
    emoji: '🏗️',
    color: '#f59e0b',
    description: 'Master HLD + LLD to clear SDE-2 and senior rounds',
    duration: '2–3 months',
    premium: true,
    phases: [
      {
        id: 'hld-basics',
        label: 'Phase 1 — HLD Fundamentals',
        weeks: '1–3',
        color: '#f59e0b',
        steps: [
          { id: 'scalability-101', label: 'Horizontal vs vertical scaling, load balancers', done: false },
          { id: 'caching-patterns', label: 'Cache-aside, write-through, write-back patterns', done: false },
          { id: 'cap-theorem', label: 'CAP theorem and real-world trade-offs', done: false },
          { id: 'database-choice', label: 'SQL vs NoSQL: when to use what', done: false },
          { id: 'cdn-and-dns', label: 'How CDNs, DNS, and edge computing work', done: false },
        ],
      },
      {
        id: 'hld-designs',
        label: 'Phase 2 — Classic HLD Designs',
        weeks: '4–7',
        color: '#ec4899',
        steps: [
          { id: 'url-shortener', label: 'Design URL Shortener (tinyurl)', done: false },
          { id: 'chat-system', label: 'Design WhatsApp / Chat System', done: false },
          { id: 'instagram', label: 'Design Instagram / Photo Sharing', done: false },
          { id: 'netflix', label: 'Design Netflix / Video Streaming', done: false },
          { id: 'uber', label: 'Design Uber / Ride Sharing', done: false },
          { id: 'search-engine', label: 'Design Google Search / Typeahead', done: false },
        ],
      },
      {
        id: 'lld',
        label: 'Phase 3 — Low Level Design',
        weeks: '8–10',
        color: '#6366f1',
        steps: [
          { id: 'solid-principles', label: 'SOLID principles with real examples', done: false },
          { id: 'design-patterns', label: '10 essential design patterns: Factory, Singleton, Observer, Strategy...', done: false },
          { id: 'lld-parking', label: 'Design Parking Lot system', done: false },
          { id: 'lld-books', label: 'Design Library Management / BookMyShow', done: false },
          { id: 'lld-snake', label: 'Design Snake & Ladder / Chess', done: false },
        ],
      },
    ],
  },
];
