// ─── CAREER ROADMAPS — Structured paths from service to product ───────────────

export const ROADMAPS = [
  // ─────────────────────────────────────────────────────────────────────────
  // SDE-2 PRODUCT
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'sde2-product',
    label: 'SDE-2 at Product Company',
    emoji: '🚀',
    track: 'sde',
    color: '#10b981',
    description: 'The complete path to crack SDE-2 at Amazon, Flipkart, Swiggy, or Zomato',
    duration: '4–6 months',
    premium: false,
    phases: [
      {
        id: 'foundation',
        label: 'Phase 1 — Foundation',
        weeks: '1–4',
        color: '#10b981',
        steps: [
          { id: 'setup-leetcode',    label: 'Create LeetCode account, solve 5 easy problems' },
          { id: 'learn-complexity',  label: 'Master Big-O analysis (time & space)' },
          { id: 'arrays-basics',     label: 'Complete Arrays & Strings section in DSA tracker' },
          { id: 'first-20',          label: 'Solve first 20 LeetCode Easy problems' },
          { id: 'cs-fundamentals',   label: 'Revise OS basics: processes, threads, memory' },
          { id: 'git-basics',        label: 'Get comfortable with Git: branch, merge, rebase' },
        ],
      },
      {
        id: 'core-dsa',
        label: 'Phase 2 — Core DSA',
        weeks: '5–10',
        color: '#6366f1',
        steps: [
          { id: 'binary-search-done', label: 'Complete Binary Search section (all 7 topics)' },
          { id: 'linked-list-done',   label: 'Complete Linked Lists section' },
          { id: 'trees-done',         label: 'Complete Trees & BST section' },
          { id: 'solve-50',           label: 'Reach 50 LeetCode problems solved' },
          { id: 'stack-queue-done',   label: 'Complete Stack, Queue & Heap section' },
          { id: 'hashing-done',       label: 'Complete Hashing & Sorting section' },
          { id: 'mock-interviews',    label: 'Do 5 mock interviews on Pramp / interviewing.io' },
        ],
      },
      {
        id: 'advanced-dsa',
        label: 'Phase 3 — Advanced DSA',
        weeks: '11–16',
        color: '#8b5cf6',
        steps: [
          { id: 'graphs-done',     label: 'Complete Graphs section' },
          { id: 'dp-done',         label: 'Complete Dynamic Programming section' },
          { id: 'backtrack-done',  label: 'Complete Backtracking section' },
          { id: 'solve-150',       label: 'Reach 150 LeetCode problems solved' },
          { id: 'contest-5',       label: 'Participate in 5 LeetCode weekly contests' },
          { id: 'company-wise',    label: 'Solve Amazon/Flipkart tagged problems on LeetCode' },
        ],
      },
      {
        id: 'interviews',
        label: 'Phase 4 — Interview Readiness',
        weeks: '17–20',
        color: '#f59e0b',
        steps: [
          { id: 'resume-update',      label: 'Update resume with impact numbers (not just duties)' },
          { id: 'sd-basics',          label: 'Learn System Design basics (HLD)' },
          { id: 'behavioral-prep',    label: 'Prepare STAR-format stories for 10 behavioral questions' },
          { id: 'apply-10',           label: 'Apply to 10 companies via LinkedIn / Naukri' },
          { id: 'referrals',          label: 'Get 3+ referrals from alumni at product companies' },
          { id: 'offer',              label: '🎉 Land the offer!' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // FRONTEND
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'frontend-specialist',
    label: 'Frontend Engineer',
    emoji: '🎨',
    track: 'frontend',
    color: '#ec4899',
    description: 'Become a frontend specialist — React, performance, and system design',
    duration: '3–5 months',
    premium: false,
    phases: [
      {
        id: 'js-mastery',
        label: 'Phase 1 — JavaScript Mastery',
        weeks: '1–4',
        color: '#ec4899',
        steps: [
          { id: 'js-closures',   label: 'Deeply understand closures, scope, hoisting' },
          { id: 'js-async',      label: 'Master Promises, async/await, event loop' },
          { id: 'js-prototype',  label: 'Understand prototypal inheritance & this keyword' },
          { id: 'es6-plus',      label: 'Destructuring, spread, modules, optional chaining' },
          { id: 'dom-apis',      label: 'Practice DOM manipulation without frameworks' },
        ],
      },
      {
        id: 'react-advanced',
        label: 'Phase 2 — React Deep Dive',
        weeks: '5–9',
        color: '#6366f1',
        steps: [
          { id: 'react-hooks',      label: 'Master all hooks: useState, useEffect, useRef, useMemo, useCallback' },
          { id: 'react-patterns',   label: 'Learn compound components, render props, HOC patterns' },
          { id: 'state-mgmt',       label: 'Learn Redux Toolkit or Zustand for state management' },
          { id: 'react-query',      label: 'Use TanStack Query for data fetching & caching' },
          { id: 'build-3-projects', label: 'Build 3 portfolio projects (not todo apps!)' },
        ],
      },
      {
        id: 'performance',
        label: 'Phase 3 — Performance & Browser',
        weeks: '10–14',
        color: '#10b981',
        steps: [
          { id: 'core-web-vitals', label: 'Learn Core Web Vitals: LCP, CLS, FID/INP' },
          { id: 'lazy-loading',    label: 'Implement lazy loading, code splitting, tree shaking' },
          { id: 'browser-render',  label: 'Understand critical rendering path' },
          { id: 'lighthouse',      label: 'Get a Lighthouse score of 90+ on your projects' },
          { id: 'typescript',      label: 'Add TypeScript to at least one project' },
        ],
      },
      {
        id: 'fe-interviews',
        label: 'Phase 4 — Frontend Interview Prep',
        weeks: '15–18',
        color: '#f59e0b',
        steps: [
          { id: 'machine-coding',   label: 'Practice 20 machine coding problems' },
          { id: 'fe-system-design', label: 'Frontend system design: component libraries, micro-frontends' },
          { id: 'lld-practice',     label: 'Design Typeahead, Infinite Scroll, Drag-Drop component' },
          { id: 'dsa-frontend',     label: 'Solve 80+ LeetCode problems (JS focus)' },
          { id: 'fe-offer',         label: '🎉 Get that frontend role!' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // BACKEND
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'backend-specialist',
    label: 'Backend Engineer',
    emoji: '⚙️',
    track: 'backend',
    color: '#6366f1',
    description: 'Build robust backend systems — APIs, databases, and microservices',
    duration: '4–6 months',
    premium: false,
    phases: [
      {
        id: 'backend-foundation',
        label: 'Phase 1 — Backend Foundation',
        weeks: '1–4',
        color: '#6366f1',
        steps: [
          { id: 'http-rest',      label: 'Master HTTP methods, status codes, REST principles' },
          { id: 'node-or-java',   label: 'Pick Node.js or Java Spring Boot and get comfortable' },
          { id: 'build-crud-api', label: 'Build a CRUD REST API with authentication' },
          { id: 'sql-basics',     label: 'Write complex SQL: JOINs, subqueries, indexes, EXPLAIN' },
          { id: 'auth-jwt',       label: 'Implement JWT auth with refresh tokens' },
        ],
      },
      {
        id: 'databases',
        label: 'Phase 2 — Databases & Caching',
        weeks: '5–9',
        color: '#10b981',
        steps: [
          { id: 'sql-advanced', label: 'Learn transactions, ACID, isolation levels' },
          { id: 'nosql',        label: 'Understand MongoDB or DynamoDB for document storage' },
          { id: 'redis',        label: 'Use Redis for caching, rate limiting, sessions' },
          { id: 'db-design',    label: 'Design 3 real-world database schemas' },
          { id: 'orm',          label: 'Use Prisma, Hibernate, or TypeORM — understand N+1 problem' },
        ],
      },
      {
        id: 'system-thinking',
        label: 'Phase 3 — System Thinking',
        weeks: '10–16',
        color: '#8b5cf6',
        steps: [
          { id: 'microservices',  label: 'Understand microservices vs monolith trade-offs' },
          { id: 'message-queues', label: 'Learn Kafka or RabbitMQ for async processing' },
          { id: 'docker-be',      label: 'Dockerize your applications' },
          { id: 'monitoring',     label: 'Set up logging and monitoring (Prometheus / Grafana basics)' },
          { id: 'sd-30',          label: 'Study 30 system design questions' },
        ],
      },
      {
        id: 'be-interviews',
        label: 'Phase 4 — Interview Prep',
        weeks: '17–20',
        color: '#f59e0b',
        steps: [
          { id: 'dsa-150-be', label: 'Solve 150+ LeetCode problems (focus on graphs, DP)' },
          { id: 'lld-be',     label: 'Design: Parking Lot, Cab Booking, Rate Limiter' },
          { id: 'hld-be',     label: 'Design: URL Shortener, Twitter Feed, Uber' },
          { id: 'be-offer',   label: '🎉 Land your backend role!' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // DEVOPS — Comprehensive
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'devops',
    label: 'DevOps Engineer',
    emoji: '🔧',
    track: 'devops',
    color: '#f97316',
    description: 'From zero to job-ready DevOps engineer — Linux, Docker, K8s, AWS, Terraform, CI/CD',
    duration: '6–8 months',
    premium: false,
    phases: [
      {
        id: 'devops-linux',
        label: 'Phase 1 — Linux & Networking Fundamentals',
        weeks: '1–4',
        color: '#f97316',
        steps: [
          { id: 'linux-cli',       label: 'Master Linux CLI: ls, grep, find, awk, sed, pipes' },
          { id: 'linux-fs',        label: 'Understand Linux file system hierarchy (/, /etc, /var, /proc)' },
          { id: 'linux-perms',     label: 'File permissions: chmod, chown, sudo, users & groups' },
          { id: 'bash-scripting',  label: 'Write bash scripts: variables, loops, conditionals, functions' },
          { id: 'cron-jobs',       label: 'Schedule tasks with cron and systemd timers' },
          { id: 'ssh-keys',        label: 'SSH: key-based auth, port forwarding, config file' },
          { id: 'networking-101',  label: 'Networking: TCP/IP, DNS, HTTP/HTTPS, ports, firewalls' },
          { id: 'process-mgmt',    label: 'Process management: ps, top, kill, systemctl, journalctl' },
        ],
      },
      {
        id: 'devops-vcs-cicd',
        label: 'Phase 2 — Git & CI/CD Basics',
        weeks: '5–8',
        color: '#6366f1',
        steps: [
          { id: 'git-advanced',     label: 'Git: branching strategies, GitFlow, rebasing, cherry-pick' },
          { id: 'github-actions',   label: 'Build CI/CD pipeline with GitHub Actions (lint, test, deploy)' },
          { id: 'jenkins-basics',   label: 'Set up Jenkins, create a declarative pipeline (Jenkinsfile)' },
          { id: 'gitlab-cicd',      label: 'Understand GitLab CI/CD .gitlab-ci.yml structure' },
          { id: 'artifact-mgmt',    label: 'Artifact management: JFrog Artifactory or Nexus basics' },
          { id: 'sonarqube',        label: 'Integrate code quality checks with SonarQube' },
        ],
      },
      {
        id: 'devops-containers',
        label: 'Phase 3 — Docker & Containerization',
        weeks: '9–12',
        color: '#06b6d4',
        steps: [
          { id: 'docker-basics',   label: 'Docker: images, containers, Dockerfile best practices' },
          { id: 'docker-compose',  label: 'Docker Compose: multi-container apps, networks, volumes' },
          { id: 'docker-registry', label: 'Push/pull images: Docker Hub, AWS ECR, GitHub Packages' },
          { id: 'docker-security', label: 'Container security: non-root users, image scanning, secrets' },
          { id: 'docker-project',  label: 'Containerize a full-stack app (frontend + backend + DB)' },
        ],
      },
      {
        id: 'devops-kubernetes',
        label: 'Phase 4 — Kubernetes (K8s)',
        weeks: '13–18',
        color: '#3b82f6',
        steps: [
          { id: 'k8s-core',         label: 'K8s architecture: nodes, pods, deployments, services, ingress' },
          { id: 'k8s-config',       label: 'ConfigMaps, Secrets, PersistentVolumes, PVCs' },
          { id: 'k8s-scaling',      label: 'HPA, VPA, resource limits, node affinity' },
          { id: 'k8s-networking',   label: 'K8s networking: CNI plugins, NetworkPolicy, DNS' },
          { id: 'helm-charts',      label: 'Package apps with Helm: charts, values, templating' },
          { id: 'k8s-debug',        label: 'Troubleshooting K8s: kubectl logs, exec, describe, events' },
          { id: 'k8s-project',      label: 'Deploy a microservices app on Kubernetes (minikube or kind)' },
        ],
      },
      {
        id: 'devops-cloud',
        label: 'Phase 5 — Cloud (AWS)',
        weeks: '19–24',
        color: '#f59e0b',
        steps: [
          { id: 'aws-core',         label: 'AWS core: EC2, S3, RDS, VPC, IAM, Security Groups' },
          { id: 'aws-networking',   label: 'VPC deep dive: subnets, NAT gateway, route tables, peering' },
          { id: 'aws-compute',      label: 'ECS, EKS, Lambda, Auto Scaling Groups, Load Balancers' },
          { id: 'aws-storage',      label: 'S3 policies, EBS, EFS, RDS Multi-AZ vs Read Replicas' },
          { id: 'aws-serverless',   label: 'Serverless: Lambda + API Gateway + DynamoDB stack' },
          { id: 'aws-ccp',          label: 'Pass AWS Cloud Practitioner (CLF-C02) certification' },
          { id: 'aws-saa',          label: 'Study for AWS Solutions Architect Associate (SAA-C03)' },
        ],
      },
      {
        id: 'devops-iac',
        label: 'Phase 6 — Infrastructure as Code',
        weeks: '25–28',
        color: '#8b5cf6',
        steps: [
          { id: 'terraform-basics',   label: 'Terraform: providers, resources, variables, outputs, state' },
          { id: 'terraform-modules',  label: 'Terraform modules: reusability, remote state, workspaces' },
          { id: 'terraform-aws',      label: 'Provision VPC + EC2 + RDS on AWS with Terraform' },
          { id: 'ansible-basics',     label: 'Ansible: inventory, playbooks, roles, handlers, templates' },
          { id: 'ansible-deploy',     label: 'Use Ansible to configure servers and deploy applications' },
          { id: 'gitops',             label: 'GitOps with ArgoCD: declarative K8s deployments from Git' },
        ],
      },
      {
        id: 'devops-monitoring',
        label: 'Phase 7 — Monitoring & Observability',
        weeks: '29–32',
        color: '#10b981',
        steps: [
          { id: 'prometheus',         label: 'Prometheus: metrics, PromQL, alerting rules, Alertmanager' },
          { id: 'grafana',            label: 'Build Grafana dashboards for infrastructure & app metrics' },
          { id: 'elk-stack',          label: 'ELK Stack: ship logs with Filebeat, search in Kibana' },
          { id: 'distributed-tracing',label: 'Distributed tracing with Jaeger or OpenTelemetry' },
          { id: 'sre-concepts',       label: 'SRE: SLOs, SLIs, SLAs, error budgets, incident runbooks' },
          { id: 'devops-interview',   label: 'Practice 50 DevOps scenario interview questions' },
          { id: 'devops-offer',       label: '🎉 Land your DevOps / SRE role!' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // DATA ANALYST
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'data-analyst',
    label: 'Data Analyst',
    emoji: '📊',
    track: 'data',
    color: '#a78bfa',
    description: 'From service company to data analyst at a product firm — SQL, Python, dashboards, and storytelling',
    duration: '4–5 months',
    premium: false,
    phases: [
      {
        id: 'da-sql',
        label: 'Phase 1 — SQL Mastery',
        weeks: '1–3',
        color: '#a78bfa',
        steps: [
          { id: 'sql-basics-da',    label: 'SELECT, WHERE, GROUP BY, HAVING, ORDER BY — master all' },
          { id: 'sql-joins',        label: 'All JOIN types: INNER, LEFT, RIGHT, FULL OUTER, SELF, CROSS' },
          { id: 'sql-subqueries',   label: 'Subqueries, CTEs (WITH clause), correlated subqueries' },
          { id: 'sql-window',       label: 'Window functions: ROW_NUMBER, RANK, LAG, LEAD, PARTITION BY' },
          { id: 'sql-agg',          label: 'Aggregations: COUNT, SUM, AVG, MIN, MAX with NULL handling' },
          { id: 'sql-practice',     label: 'Solve 50+ SQL problems on LeetCode / StrataScratch / HackerRank' },
          { id: 'sql-perf',         label: 'Query optimization: EXPLAIN, indexes, avoiding full scans' },
        ],
      },
      {
        id: 'da-python',
        label: 'Phase 2 — Python for Data',
        weeks: '4–7',
        color: '#6366f1',
        steps: [
          { id: 'python-basics-da', label: 'Python fundamentals: lists, dicts, loops, functions, comprehensions' },
          { id: 'pandas-basics',    label: 'Pandas: read CSV/Excel, filter, sort, groupby, merge DataFrames' },
          { id: 'pandas-advanced',  label: 'Pandas: pivot tables, apply(), lambda, datetime handling' },
          { id: 'numpy-basics',     label: 'NumPy: arrays, vectorized operations, broadcasting' },
          { id: 'data-cleaning',    label: 'Handle missing values, duplicates, outliers, encoding categoricals' },
          { id: 'jupyter-nb',       label: 'Structure analysis in Jupyter Notebooks professionally' },
          { id: 'first-eda',        label: 'Complete first full EDA on a real dataset (Kaggle)' },
        ],
      },
      {
        id: 'da-viz',
        label: 'Phase 3 — Data Visualization & Storytelling',
        weeks: '8–10',
        color: '#ec4899',
        steps: [
          { id: 'matplotlib',     label: 'Matplotlib & Seaborn: line, bar, scatter, heatmap, box plots' },
          { id: 'plotly',         label: 'Plotly for interactive charts in notebooks' },
          { id: 'tableau',        label: 'Tableau Public: dimensions, measures, calculated fields, dashboards' },
          { id: 'powerbi',        label: 'Power BI Desktop: DAX basics, relationships, reports' },
          { id: 'dashboard-proj', label: 'Build a business dashboard with 5+ charts telling a story' },
          { id: 'data-story',     label: 'Present insights to a non-technical audience (practice 3 times)' },
        ],
      },
      {
        id: 'da-stats',
        label: 'Phase 4 — Statistics & A/B Testing',
        weeks: '11–13',
        color: '#10b981',
        steps: [
          { id: 'descriptive-stats', label: 'Mean, median, mode, std deviation, variance, percentiles' },
          { id: 'distributions',     label: 'Normal, binomial, Poisson distributions & their applications' },
          { id: 'hypothesis-test',   label: 'Hypothesis testing: null/alternate hypothesis, p-value, alpha' },
          { id: 'ttest-chi',         label: 'T-test, chi-square, ANOVA — when to use each' },
          { id: 'ab-testing',        label: 'Design and analyze an A/B test: sample size, significance' },
          { id: 'correlation',       label: 'Correlation vs causation, Pearson & Spearman correlation' },
        ],
      },
      {
        id: 'da-bi',
        label: 'Phase 5 — Business Intelligence & BI Tools',
        weeks: '14–16',
        color: '#f59e0b',
        steps: [
          { id: 'data-warehouse',   label: 'Star schema, snowflake schema, OLAP vs OLTP' },
          { id: 'etl-basics',       label: 'ETL/ELT pipeline concepts and tools (dbt basics)' },
          { id: 'metabase',         label: 'Set up Metabase or Looker Studio with a real database' },
          { id: 'excel-advanced',   label: 'Excel: VLOOKUP, INDEX-MATCH, pivot tables, Power Query' },
          { id: 'kpi-metrics',      label: 'Define KPIs for an e-commerce / fintech business' },
          { id: 'sql-bi-tools',     label: 'Write SQL queries in Redash, Superset, or BigQuery console' },
        ],
      },
      {
        id: 'da-portfolio',
        label: 'Phase 6 — Portfolio & Interview Prep',
        weeks: '17–20',
        color: '#f97316',
        steps: [
          { id: 'kaggle-proj',      label: 'Complete 2 end-to-end projects on Kaggle with writeups' },
          { id: 'github-portfolio', label: 'Host all projects on GitHub with clean READMEs' },
          { id: 'sql-interview',    label: 'Practice 50 SQL interview questions (window functions focus)' },
          { id: 'case-studies',     label: 'Practice 5 product analytics case studies (metrics, funnels)' },
          { id: 'resume-da',        label: 'Resume: quantify every bullet (e.g., "reduced churn by 12%")' },
          { id: 'da-offer',         label: '🎉 Land your Data Analyst role at a product company!' },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SYSTEM DESIGN (Premium)
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'system-design',
    label: 'System Design Mastery',
    emoji: '🏗️',
    track: 'sde',
    color: '#f59e0b',
    description: 'Master HLD + LLD to clear SDE-2 and senior rounds',
    duration: '2–3 months',
    premium: true,
    phases: [
      {
        id: 'hld-basics',
        label: 'Phase 1 — HLD Fundamentals',
        weeks: '1–3',
        color: '#f59e0b',
        steps: [
          { id: 'scalability-101',  label: 'Horizontal vs vertical scaling, load balancers' },
          { id: 'caching-patterns', label: 'Cache-aside, write-through, write-back patterns' },
          { id: 'cap-theorem',      label: 'CAP theorem and real-world trade-offs' },
          { id: 'database-choice',  label: 'SQL vs NoSQL: when to use what' },
          { id: 'cdn-and-dns',      label: 'How CDNs, DNS, and edge computing work' },
        ],
      },
      {
        id: 'hld-designs',
        label: 'Phase 2 — Classic HLD Designs',
        weeks: '4–7',
        color: '#ec4899',
        steps: [
          { id: 'url-shortener', label: 'Design URL Shortener (tinyurl)' },
          { id: 'chat-system',   label: 'Design WhatsApp / Chat System' },
          { id: 'instagram',     label: 'Design Instagram / Photo Sharing' },
          { id: 'netflix',       label: 'Design Netflix / Video Streaming' },
          { id: 'uber',          label: 'Design Uber / Ride Sharing' },
          { id: 'search-engine', label: 'Design Google Search / Typeahead' },
        ],
      },
      {
        id: 'lld',
        label: 'Phase 3 — Low Level Design',
        weeks: '8–10',
        color: '#6366f1',
        steps: [
          { id: 'solid-principles',  label: 'SOLID principles with real examples' },
          { id: 'design-patterns',   label: '10 essential design patterns: Factory, Singleton, Observer…' },
          { id: 'lld-parking',       label: 'Design Parking Lot system' },
          { id: 'lld-books',         label: 'Design Library Management / BookMyShow' },
          { id: 'lld-snake',         label: 'Design Snake & Ladder / Chess' },
        ],
      },
    ],
  },
];
